/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pl.polsl.kamil.Window;

import pl.polsl.kamil.Model.AllTeams;
import pl.polsl.kamil.Model.AllGames;

/**
 * Class responsible for showing menu window
 *
 * @author Kamil Skupien
 * @version 1.0
 */
public class MainWindow extends javax.swing.JFrame {

    private AllGames table;
    private AllTeams teams;

    /**
     * Main constructor that saves table and teams objects
     *
     * @param Table object that holds whole game table
     * @param Teams object that holds all teams that appears in application
     */
    public MainWindow(AllGames Table, AllTeams Teams) {
        initComponents();
        this.table = Table;
        this.teams = Teams;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        addTeamButton = new javax.swing.JButton();
        addGameButton = new javax.swing.JButton();
        printTeamsButton = new javax.swing.JButton();
        printGamesButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addTeamButton.setText("Dodaj druzyne");
        addTeamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTeamButtonActionPerformed(evt);
            }
        });

        addGameButton.setText("Dodaj mecz");
        addGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGameButtonActionPerformed(evt);
            }
        });

        printTeamsButton.setText("Wyswietl druzyny");
        printTeamsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printTeamsButtonActionPerformed(evt);
            }
        });

        printGamesButton.setText("Wyswietl mecze");
        printGamesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printGamesButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Wyjscie");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Football Stats App Menu ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addTeamButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addGameButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(printTeamsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(printGamesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(240, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(227, 227, 227))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(addTeamButton)
                .addGap(18, 18, 18)
                .addComponent(addGameButton)
                .addGap(18, 18, 18)
                .addComponent(printTeamsButton)
                .addGap(18, 18, 18)
                .addComponent(printGamesButton)
                .addGap(18, 18, 18)
                .addComponent(exitButton)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Method that close current window and opens addTeam window
     *
     * @param evt event of pushing that button
     */
    private void addTeamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTeamButtonActionPerformed

        dispose();
        java.awt.EventQueue.invokeLater(() -> {
            new AddTeam(table, teams).setVisible(true);
        });
    }//GEN-LAST:event_addTeamButtonActionPerformed

    /**
     * Method that close current window
     *
     * @param evt event of pushing that button
     */
    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * Method that close current window and opens printTeams window
     *
     * @param evt event of pushing that button
     */
    private void printTeamsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printTeamsButtonActionPerformed

        dispose();

        java.awt.EventQueue.invokeLater(() -> {
            new PrintTeams(table, teams).setVisible(true);
        });
    }//GEN-LAST:event_printTeamsButtonActionPerformed

    /**
     * Method that close current window and opens printGames window
     *
     * @param evt event of pushing that button
     */
    private void printGamesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printGamesButtonActionPerformed

        dispose();

        java.awt.EventQueue.invokeLater(() -> {
            new PrintGames(table, teams).setVisible(true);
        });

    }//GEN-LAST:event_printGamesButtonActionPerformed
    /**
     * Method that close current window and opens addGame window
     *
     * @param evt event of pushing that button
     */
    private void addGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGameButtonActionPerformed
        dispose();

        java.awt.EventQueue.invokeLater(() -> {
            new AddGame(table, teams).setVisible(true);
        });
    }//GEN-LAST:event_addGameButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addGameButton;
    private javax.swing.JButton addTeamButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JButton printGamesButton;
    private javax.swing.JButton printTeamsButton;
    // End of variables declaration//GEN-END:variables

}
